### PR TITLE
Semua setengah matang

### PR DESCRIPTION
**Pull request by Raruu**
# A-Keep's Masterpiece

### CODE REVIEW

**Review by Khip01 — CHANGES_REQUESTED** [review]
Goreng lagi biar matang chef!🧑‍🍳🍳

**Comment by Khip01** [comment]
acc 3000000 ? 👊 😎

**Comment by Raruu** [comment]
> acc 3000000 ? 👊 😎

**Review by Khip01 — APPROVED** [review]
Good! Great Changes!
Mahkotamu lagi di anter kurir king 👑

**Pull request merged**
